server:
  port: 9000

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/api/main/**
        - id: scoring-service
          uri: lb://scoring-service
          predicates:
            - Path=/api/scoring/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mail:
      enabled: false
    redis:
      enabled: false