server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

management:
  endpoints:
    web:
      exposure:
        include: "*"

        springdoc:
          api-docs:
            path: /api-docs
          swagger-ui:
            path: /swagger-ui.html
            enabled: true
            try-it-out-enabled: true
            operations-sorter: method
            tags-sorter: alpha
            display-request-duration: true